# 编译目标: 最终生成可执行文件 max30102_service
max30102_service: max30102_service.c algorithm.c algorithm.h
	arm-none-linux-gnueabihf-gcc -O2 -Wall -o max30102_service max30102_service.c algorithm.c

clean:
	rm -f max30102_service
